export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const INCREMENT_QUANTITY_PRODUCT_ON_CART = 'INCREMENT_QUANTITY_PRODUCT_ON_CART'
export const DECREMENT_QUANTITY_PRODUCT_ON_CART = 'DECREMENT_QUANTITY_PRODUCT_ON_CART'
